// Copyright (C) 2022  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.

// Generated by Quartus Prime Version 21.1.1 Build 850 06/23/2022 SJ Lite Edition
// Created on Thu Feb 15 10:44:55 2024

// synthesis message_off 10175

`timescale 1ns/1ns

module statemachine (
    reset,clock,X,
    LED[2:0]);

    input reset;
    input clock;
    input X;
    tri0 reset;
    tri0 X;
    output [2:0] LED;
    reg [2:0] LED;
    reg [3:0] fstate;
    reg [3:0] reg_fstate;
    parameter state1=0,state2=1,state3=2,state4=3;

    always @(posedge clock)
    begin
        if (clock) begin
            fstate <= reg_fstate;
        end
    end

    always @(fstate or reset or X)
    begin
        if (reset) begin
            reg_fstate <= state1;
            LED <= 3'b000;
        end
        else begin
            LED <= 3'b000;
            case (fstate)
                state1: begin
                    if ((X == 1'b1))
                        reg_fstate <= state2;
                    // Inserting 'else' block to prevent latch inference
                    else
                        reg_fstate <= state1;

                    LED <= 3'b000;
                    LED <= 3'b100;
                end
                state2: begin
                    if ((X == 1'b1))
                        reg_fstate <= state3;
                    // Inserting 'else' block to prevent latch inference
                    else
                        reg_fstate <= state2;

                    LED <= 3'b001;
                end
                state3: begin
                    if ((X == 1'b1))
                        reg_fstate <= state4;
                    // Inserting 'else' block to prevent latch inference
                    else
                        reg_fstate <= state3;

                    LED <= 3'b010;
                end
                state4: begin
                    if ((X == 1'b1))
                        reg_fstate <= state1;
                    // Inserting 'else' block to prevent latch inference
                    else
                        reg_fstate <= state4;

                    LED <= 3'b011;
                end
                default: begin
                    LED <= 3'bxxx;
                    $display ("Reach undefined state");
                end
            endcase
        end
    end
endmodule // statemachine
